version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mage:
    image: mageai/mageai:latest
    container_name: mage_ai
    environment:
      USER_CODE_PATH: /home/src/pipeline_test
      MAGE_CLUSTER_TYPE: none
    ports:
      - "6789:6789"
    volumes:
      - .:/home/src/pipeline_test
    depends_on:
      postgres:
        condition: service_healthy
    command: mage start pipeline_test

volumes:
  postgres_data: